steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$_PROJECT_ID/slack-p-server:$_BUILD_NUM', '-f', 'Dockerfile.srv', '.']
images: ['gcr.io/$_PROJECT_ID/slack-p-server:$_BUILD_NUM']