version: 2

jobs:
  install:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
        command: |
          ssh -i ~/.ssh/id_cron gong023@150.95.181.231 'bash ' < ./install.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - install:
          filters:
            branches:
              only: master
