version: 2

gcloud_auth: &gcloud_auth
  name: auth
  command: |
    echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
    gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
    gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
    gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
    gcloud container clusters get-credentials --project=${GOOGLE_PROJECT_ID} --region=${GOOGLE_COMPUTE_ZONE} ${GOOGLE_CLUSTER}

jobs:
  build_worker:
    docker:
      - image: gcr.io/cloud-builders/gcloud
    steps:
      - checkout
      - run:
          <<: *gcloud_auth
      - run:
          name: build and push
          command: |
            gcloud container builds submit \
              --config=cloudbuild.worker.yaml \
              --substitutions=_PROJECT_ID=${GOOGLE_PROJECT_ID},_BUILD_NUM=${CIRCLE_WORKFLOW_ID} .
  build_server:
    docker:
      - image: gcr.io/cloud-builders/gcloud
    steps:
      - checkout
      - run:
          <<: *gcloud_auth
      - run:
          name: build and push
          command: |
            gcloud container builds submit \
              --config=cloudbuild.server.yaml \
              --substitutions=_PROJECT_ID=${GOOGLE_PROJECT_ID},_BUILD_NUM=${CIRCLE_WORKFLOW_ID} .
  deploy:
    docker:
      - image: devth/helm:latest
    steps:
      - checkout
      - run:
          <<: *gcloud_auth
      - run:
          name: helm
          command: |
            helm upgrade \
              --install \
              --set ProjectId=${GOOGLE_PROJECT_ID},BuildNum=${CIRCLE_WORKFLOW_ID},Host=${HOST} \
              cron ./manifests/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_worker:
          filters:
            branches:
              only: master
      - build_server:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build_worker
            - build_server
          filters:
            branches:
              only: master
