version: 2

jobs:
  server:
    machine:
      enabled: true
    steps:
      - checkout
      - run: ssh -i ~/.ssh/id_cron gong023@150.95.181.231 'bash ' < ./server.sh
  deploy:
    docker:
      - image: devth/helm
    steps:
      - checkout
      - run:
          name: auth
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud container clusters get-credentials --project=${GOOGLE_PROJECT_ID} --region=${GOOGLE_COMPUTE_ZONE} ${GOOGLE_CLUSTER}
      - run:
          name: build and push
          command: |
            gcloud container builds submit -t gcr.io/${GOOGLE_PROJECT_ID}/slack-p:${CIRCLE_BUILD_NUM} .
      - run:
          name: helm
          command: |
            helm upgrade \
              --install \
              --set ProjectId=${GOOGLE_PROJECT_ID},BuildNum=${CIRCLE_BUILD_NUM} \
              cron ./manifests/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - server:
          filters:
            branches:
              only: master
      - deploy:
          filters:
            branches:
              only: master
