apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: default
spec:
  secretName: ingress-tls
  issuerRef:
    name: cert-issuer-prod
  commonName: "{{ .Values.DnsName }}"
  dnsNames:
  - "{{ .Values.DnsName }}"
  acme:
    config:
    - dns01:
        provider: cert-dns
      domains:
      - "{{ .Values.DnsName }}"
