apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: cert-issuer-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: gon.gong.gone@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
    dns01:
      providers:
      - name: cert-dns
        clouddns:
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: key.json
          project: {{ .Values.ProjectId }}
