apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: server-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/issuer: cert-issuer-prod
spec:
  tls:
  - secretName: ingress-tls
    hosts:
      - {{ .Values.Host }}
  backend:
    serviceName: server-deployment
    servicePort: 8080
