apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: server-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: server-static-ip
spec:
  tls:
  - secretName: ingress-tls
    hosts:
      - {{ .Values.Host }}
  backend:
    serviceName: server-deployment
    servicePort: 8080
